---
Name: session-manager
---
SilverStripe\Security\Member:
  extensions:
    - 'Kinglozzer\SessionManager\Extensions\MemberExtension'
SilverStripe\Security\RememberLoginHash:
  extensions:
    - 'Kinglozzer\SessionManager\Extensions\RememberLoginHashExtension'
---
Name: session-manager-log-in-handler
After: '#coreauthentication'
---
SilverStripe\Core\Injector\Injector:
  Kinglozzer\SessionManager\Security\LogInAuthenticationHandler:
    properties:
      SessionVariable: activeLoginSession
  SilverStripe\Security\AuthenticationHandler:
    properties:
      Handlers:
        LoginSessionLogIn: '%$Kinglozzer\SessionManager\Security\LogInAuthenticationHandler'
---
Name: session-manager-log-out-handler
Before: '#coreauthentication'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\AuthenticationHandler:
    properties:
      Handlers:
        LoginSessionLogOut: '%$Kinglozzer\SessionManager\Security\LogOutAuthenticationHandler'
---
Name: session-manager-middleware
After: '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        GarbageCollectionMiddleware: '%$Kinglozzer\SessionManager\Control\GarbageCollectionMiddleware'
        LoginSessionMiddleware: '%$Kinglozzer\SessionManager\Control\LoginSessionMiddleware'
